---
name: CI pipeline

on:
  pull_request:
      branches:
          - main
  push:
      branches:
          - main
  workflow_dispatch:

env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
  MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
  MY_EMAIL_ADDRESS: ${{ secrets.MY_EMAIL_ADDRESS }}
  PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
  TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
    ci-pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Set up Python
              run: uv python install

            - name: Create venv
              run: uv venv

            - name: Install dependencies
              run: make install

            - name: Run pre-commit
              run: uv run pre-commit run --all-files

            - name: Create Outlook auth file
              run: echo -n "${{ secrets.O365_TOKEN_BASE64 }}" | base64 --decode >> o365_token.txt

            - name: Run pytest
              run: make test
