---
name: CI pipeline

on:
  pull_request:
      branches:
          - main
  push:
      branches:
          - main

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Set up Python
              run: uv python install

            - name: Install dependencies
              run: make install

            - name: Run pre-commit
              run: uv run pre-commit run --all-files
