---
name: CI pipeline

on:
  pull_request:
      branches:
          - main
  push:
      branches:
          - main
  workflow_dispatch:

jobs:
    ci-pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Set up Python
              run: uv python install

            - name: Install dependencies
              run: make install argument='--system'

            - name: Run pre-commit
              run: uv run pre-commit run --all-files

            - name: Run pytest
              run: make test
